### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by yin90m** [ChulhoonJang/avm_dataset#1]
Hello, I find the runnable.py doesn't contain the trained weight. Besides, I can't find the training process. How can I run the program?

**Comment by Engro39** [comment]
please refer to https://github.com/ChulhoonJang/avm_ss

**Comment by yin90m** [comment]
However, it still lacks the trained model weights to run the demo. Also, the hypes.json is hard to be completed unless reading through the codes.

**Comment by Engro39** [comment]
you can download the model referring "model download" in https://github.com/ChulhoonJang/avm_ss.
