### ISSUE TITLE
The AVM algorithm

### ISSUE THREAD

**Issue by ryan1051** [ChulhoonJang/avm_dataset#2]
hello, I am finding a good algorithm to implement the AVM. May I know your calibration and stitching algorithm to get the avm image?

**Comment by Engro39** [comment]
I have no calibration and stitching algorithms for this dataset. The AVM system provided stitched images standalone.

**Comment by ryan1051** [comment]
> I have no calibration and stitching algorithms for this dataset. The AVM system provided stitched images standalone.

Thank you anyway.
