### ISSUE TITLE
Dataset Link not access

### ISSUE THREAD

**Issue by chokkarapu** [ChulhoonJang/avm_dataset#5]
Hello Jang,

The links provided to download the dataset are unable to access, so could you kindly provide the links to download.

I look forward for your response.

Thanks,
Anil

**Comment by Engro39** [comment]
I don't think the link is broken. You should see like this capture when you click the link. Please try with other pc or laptop.

<img width="375" alt="Downloading from DiskStation" src="https://user-images.githubusercontent.com/13134640/68722351-2baf8800-0583-11ea-9cf0-4b19419fd22c.png">

**Comment by chokkarapu** [comment]
Hi Jang,

Thanks for response...
till i could see link broken as shwon in below snapshot:

![image](https://user-images.githubusercontent.com/3630515/69027241-3d19e980-09f4-11ea-9ea3-32582622df1c.png)


Kindly can you share me the link here.

Thanks,
Anil

**Comment by Engro39** [comment]
I checked the link at home and work, but it works well. I don't know why this issue occurs. Did you try to download in different locations?

**Comment by chokkarapu** [comment]
Yes I tried at my home, to open the link still it shows same issue.
If possible can u send other link ?

Thanks

**Comment by Engro39** [comment]
Unfortunately, I have no alternative link for it. Sorry.

**Comment by Ao-Lee** [comment]
it's not available at first, after trying several times, i finally managed to get the link, just try it again @chokkarapu

**Comment by kikyoyang** [comment]
@Ao-Lee could you please share me the data, i also can't get the link, thanks very much

**Comment by loseyourself-gan** [comment]
@Ao-Lee could you please share me the data, i also can't get the link, thanks very much

**Comment by Ao-Lee** [comment]
> @Ao-Lee could you please share me the data, i also can't get the link, thanks very much
@kikyoyang @loseyourself-gan the network is not stable. I managed to downloaded once. Currently I do not have the copy since I resigned and cannot access my previous company database. Sry cannot help

**Comment by loseyourself-gan** [comment]
@Ao-Lee  Anyway ,thank you ! The author has updated the link.
