### ISSUE TITLE
the dataset link is missed

### ISSUE THREAD

**Issue by plzhai** [ChulhoonJang/avm_dataset#6]

**Comment by hs7251912** [comment]
the dataset link is not available. could you share alternative dataset link?

**Comment by AbhijithSree1** [comment]
Hi, would you please reupload the dataset link?

**Comment by Engro39** [comment]
Hi all, thank you for your interest in this dataset and sorry for the late response. Please check if you can download with this [link](https://drive.google.com/drive/folders/1izgXSHUisjdJMMLz43B8vjI9-JjqTDQL?usp=sharing)
