### ISSUE TITLE
data line can't open

### ISSUE THREAD

**Issue by FangJingYunner** [ChulhoonJang/avm_dataset#7]
Hi,My location is in China,and l try this link with my vpn connected,but still can't open this link, is there any solution ?
Looking forward to your reply.

**Comment by FangJingYunner** [comment]
@ChulhoonJang l also tried http://log.acelab.org/ and http://log.acelab.org:5000/ but still can't open this link....and l have no idea how to solve it ..

**Comment by FangJingYunner** [comment]
Hi,could you please put dataset on drive.google.com?l can download avm_ss trained model in drive.google.com.Thank you very much!!

**Comment by loseyourself-gan** [comment]
@FangJingYunner I have met the same problem . Do you solve it?

**Comment by Engro39** [comment]
Hi all, thank you for your interest in this dataset and sorry for the late response. Please check if you can download with this [link](https://drive.google.com/drive/folders/1izgXSHUisjdJMMLz43B8vjI9-JjqTDQL?usp=sharing)

**Comment by loseyourself-gan** [comment]
@ChulhoonJang  It works, thank you !
